### ISSUE TITLE
 Implement the ability to remove a single point from the graph 

### ISSUE THREAD

**Issue by grochot** [grochot/spinlab_measurement#42]

**Comment by Did-Mas** [comment]
I started experimenting with the possibility of removing points on the "remove_points" branch.

So far, I've managed to implement a change in the appearance of points when hovering with the mouse, and the ability to delete points with a left-click. However, at this stage, these functions only modify the data stored by the chart widget. All points are still present in the file. As a result, it's currently not possible to delete points during measurement because the deletions are overridden by the automatic data fetching from the file during the measurement.

I'm considering the best way to implement point removal. One of the better solutions seems to be adding a "point removal mode" toggle to the chart's context menu, allowing point deletion only when it's enabled. I'm also unsure whether point deletion should always result in removal from the file, but I think it might be necessary for further analysis. I could also try to offer both options: hiding a point without removing it from the file, and completely deleting it.

I'm open to suggestions on how to implement this functionality in detail.
